### ISSUE TITLE
Firebase not connecting

### ISSUE THREAD

**Issue by suasb52** [ssvas1997/Comp_Quiz_Android#1]
Hi, Its not connecting to firebase database, I have created project on firebase and added service.json file in project as well changed dependencies but still its not creating database in firebase. 
When I start app and try to signup user it always give and error "enter the unique user name"
Can you kindly check it. Guide me how I can resolve this issue.

Thanks

**Comment by ssvas1997** [comment]
Use small case letters along with some numbers to create a username, Also check in firebase if there is a user created when you tried for the first attempt and still you are trying to register using the same username,

**Comment by suasb52** [comment]
Hi, I have tried small case letters with numbers as well small and big letter with numbers and without numbers but its giving same unique username error in. Database is empty no user created in it.

**Comment by ssvas1997** [comment]
Just try to modify the logic for user sign-up where validation of a unique user is done. Try to come up with a logic of your own.
