### ISSUE TITLE
Username already taken

### ISSUE THREAD

**Issue by arngrim** [ssvas1997/Comp_Quiz_Android#3]
Hi, when a I tried to register a new user account, the app always says that the user is already taken.. When I look the code from Activity_SignUp has a mDatabase.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) .. and the return for isTaken is always TRUE.. this is because the addValueEventListener and the onDataChange works asynchronous and returns immediately, before any results are returned from the database. I found that info in Firebase docs. But I'm really new to Firebase, so do you have any ideas for solve this? I appreciate any help, thanks.

**Comment by ssvas1997** [comment]
Just comment the code 
else if(exist) part of the code. Create a new user. U will get a firebase user node created. Later check what all usernames get retrieved from the function retriveUserNames by printing a log. 
I guess there's no user in the database so it checks with an empty string and returns a true value that user exists. Hope this helps.
